export const PROJECTS = [
  {
    id: 1,
    title: "Merlines",
    description: ``,
    link: "https://dev.merlines.ru",
    img: "/img/portfolio/merlines.png",
    col: 4,
  },
  {
    id: 2,
    title: "A2Med",
    description: ``,
    img: "/img/portfolio/a2med.png",
    link: "https://lk.a2med.ru/auth/login",
    col: 4,
  },
  {
    id: 3,
    title: "East Auto",
    description: ``,
    img: "/img/portfolio/eastauto.png",
    link: "https://www.eastautollc.com/",
    col: 4,
  },
  {
    id: 4,
    title: "Ez Auto Ship",
    description: ``,
    img: "/img/portfolio/autoshipez.png",
    link: "https://autoshipez.com/",
    col: 6,
  },
  {
    id: 5,
    title: "Extensi one",
    description: ``,
    img: "/img/portfolio/extensione.png",
    link: "https://extensi-landing-new.vercel.app/",
    col: 6,
  },
  {
    id: 6,
    title: "CRM Logistic",
    description: ``,
    img: "/img/portfolio/crm-logistic.png",
    link: "https://logistics-mini.vercel.app/login",
    col: 4,
  },
  {
    id: 7,
    title: "Zikkir Buildings",
    description: ``,
    img: "/img/portfolio/zikkir.png",
    link: "https://www.zikkirbuildings.uz/",
    col: 4,
  },
  // {
  //   title: "Any Way Planet",
  //   description: ``,
  //   img: "/img/portfolio/anywayplanet.png",
  //   link: "https://anywayplanet.io/",
  //   col: 4,
  // },
  {
    title: "Olmashop",
    description: ``,
    img: "/img/portfolio/olmashop.png",
    link: "https://olmashop.uz/",
    col: 4,
  },
  {
    title: "E-medical",
    description: ``,
    img: "/img/portfolio/e-medical.webp",
    link: "https://e-medical.uz/",
    col: 6,
  },
];
