export const PROJECTS = [
  {
    id: 1,
    title: "Merlines",
    description: ``,
    link: "https://merlines.ru",
    img: "/img/portfolio/merlines.png",
    col: 4,
  },
  {
    id: 2,
    title: "A2Med",
    description: ``,
    img: "/img/portfolio/a2med.png",
    link: "https://lk.a2med.ru/auth/login",
    col: 4,
  },
  {
    id: 3,
    title: "Arbait",
    description: ``,
    img: "/img/portfolio/arbait.png",
    link: "https://arbait.uz/ru",
    col: 4,
  },
  {
    id: 4,
    title: "Alfa force",
    description: ``,
    img: "/img/portfolio/alfa-force.png",
    link: "https://crou.alfa-force.ru/",
    col: 6,
  },
  {
    id: 5,
    title: "Refine Ship",
    description: ``,
    img: "/img/portfolio/refineship.png",
    link: "https://www.refineship.com",
    col: 6,
  },
  {
    id: 6,
    title: "East Auto LLC",
    description: ``,
    img: "/img/portfolio/eastauto.png",
    link: "https://www.eastautollc.com/",
    col: 4,
  },
  {
    id: 7,
    title: "Ez Auto Ship",
    description: ``,
    img: "/img/portfolio/autoshipez.png",
    link: "https://autoshipez.com/",
    col: 4,
  },
  {
    id: 8,
    title: "Extensi one",
    description: ``,
    img: "/img/portfolio/extensione.png",
    link: "https://extensi.one/",
    col: 4,
  },
  {
    id: 9,
    title: "CRM Logistic",
    description: ``,
    img: "/img/portfolio/crm-logistic.png",
    link: "https://logistics-mini.vercel.app/login",
    col: 6,
  },
  {
    id: 10,
    title: "Zikkir Buildings",
    description: ``,
    img: "/img/portfolio/zikkir.png",
    link: "https://www.zikkirbuildings.uz/",
    col: 6,
  },

  {
    id: 11,
    title: "E-medical",
    description: ``,
    img: "/img/portfolio/e-medical.webp",
    link: "https://dashboard.e-medical.uz/",
    col: 4,
  },
  {
    id: 12,
    title: "sbumiptk",
    description: ``,
    img: "/img/portfolio/sbumiptk.png",
    link: "https://sbumiptk.uz/",
    col: 4,
  },
  {
    id: 13,
    title: "Olmashop",
    description: ``,
    img: "/img/portfolio/olmashop.png",
    link: "https://olmashop.uz/",
    col: 4,
  },
];
